version: '3'
services:
  audit-app-backend:
    image: your_docker_username/audit-app-backend:latest
    container_name: audit-app-backend
    ports:
      - "3001:3001"
    volumes:
      - /path_to_server/config.json:/home/app/config/config.json
    restart: always
